---
- name: Install packages for Zsh and git
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  register: installation
  become: true
  become_method: sudo
  with_items:
    - git
    - zsh

- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Clone oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Create a basic ~/.zshrc file
  ansible.builtin.copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  when: not stat_rc_result.stat.exists

