---

all_users:
  - user: jcampbell
    homedir: /home/jcampbell

# see the list of fonts at https://github.com/powerline/fonts
# the names must match the directory names for each font
all_fonts:
  - DejaVuSansMono
  - FiraMono
  - Hack
  - RobotoMono
  - SourceCodePro
  - UbuntuMono
