# Steps to install vpn software

- name: Import the tailscale RPM repo key
  rpm_key:
    state: present
    key: https://pkgs.tailscale.com/stable/fedora/repo.gpg
  become: yes
  become_method: sudo

- name: Add the tailscale yum repository
  yum_repository:
    name: tailscale
    description: Tailscale stable
    file: tailscale
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    gpgcheck: no
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg
  become: yes
  become_method: sudo

- name: Ensure the tailscale application is installed
  package:
    name: tailscale
    state: present
  become: yes
  become_method: sudo

- name: Start and enable the tailscaled service
  systemd:
    name: tailscaled
    enabled: yes
    daemon_reload: yes
    state: started
  become: yes
  become_method: sudo

