---
# distrobox manual install

- name: Distrobox install script
  copy:
    dest: "~/install_distrobox.sh"
    content: |
      #!/bin/sh
      curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
